@OneFit.Api_HostAddress = http://localhost:5066

GET {{OneFit.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{OneFit.Api_HostAddress}}/catalog/query
Content-Type: application/json

{
  "category": "shirt",
  "max_price_egp": 700,
  "style_tags": ["casual"],
  "in_stock_only": true,
  "limit": 3
}

###
GET {{OneFit.Api_HostAddress}}/products?category=shirt&max_price_egp=700&q=shirt&page=1&page_size=20
Accept: application/json

###
GET {{OneFit.Api_HostAddress}}/products/00c306f0-714e-4f84-9e5b-6c29029ce677
Accept: application/json

###
POST {{OneFit.Api_HostAddress}}/chatbot/message
Content-Type: application/json

{
  "shopper_id": "s1",
  "message": "عايز تيشيرت كاجوال",
  "new_chat": true
}

###
