// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OneFit.Infrastructure.Persistence.Data;

#nullable disable

namespace OneFit.Infrastructure.Migrations
{
    [DbContext(typeof(OneFitDbContext))]
    [Migration("20260909164442_IdentityTables")]
    partial class IdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Alert", b =>
                {
                    b.Property<string>("AlertId")
                        .HasColumnType("character varying")
                        .HasColumnName("alert_id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("alert_type")
                        .HasComment("PRICE_DROP or LOW_STOCK");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read")
                        .HasComment("FR-28");

                    b.Property<decimal?>("NewPriceEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("new_price_egp");

                    b.Property<decimal?>("OldPriceEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("old_price_egp");

                    b.Property<decimal?>("PercentSaved")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("percent_saved");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<string>("ShopperId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("shopper_id");

                    b.Property<string>("Size")
                        .HasColumnType("character varying")
                        .HasColumnName("size")
                        .HasComment("set only for LOW_STOCK alerts, per FR-26");

                    b.Property<DateTime?>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("triggered_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("AlertId")
                        .HasName("alerts_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "ShopperId" }, "idx_alerts_shopper_unread")
                        .HasFilter("(is_read = false)");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Brand", b =>
                {
                    b.Property<string>("BrandId")
                        .HasColumnType("character varying")
                        .HasColumnName("brand_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("BrandId")
                        .HasName("brands_pkey");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Cart", b =>
                {
                    b.Property<string>("CartId")
                        .HasColumnType("character varying")
                        .HasColumnName("cart_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ShopperId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("shopper_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'active'::character varying")
                        .HasComment("active, checked_out");

                    b.HasKey("CartId")
                        .HasName("carts_pkey");

                    b.HasIndex("ShopperId");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.CartItem", b =>
                {
                    b.Property<string>("CartItemId")
                        .HasColumnType("character varying")
                        .HasColumnName("cart_item_id");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("brand_id")
                        .HasComment("denormalized for FR-18 per-line-item brand display without a join");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("cart_id");

                    b.Property<decimal>("PriceAtAddEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_add_egp")
                        .HasComment("snapshot for FR-09/NFR-09 re-validation at checkout");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("size");

                    b.HasKey("CartItemId")
                        .HasName("cart_items_pkey");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductId", "Size");

                    b.HasIndex(new[] { "CartId" }, "idx_cart_items_cart_id");

                    b.HasIndex(new[] { "CartId", "ProductId", "Size" }, "uq_cart_item_product_size")
                        .IsUnique();

                    b.ToTable("cart_items", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("character varying")
                        .HasColumnName("order_id");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("cart_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("GrandTotalEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("grand_total_egp")
                        .HasComment("must equal SUM(sub_orders.total_egp) — enforced in application code, not by the DB");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character varying")
                        .HasColumnName("payment_status")
                        .HasDefaultValueSql("'PAID_SIMULATED'::character varying")
                        .HasComment("FR-23 — simulated only");

                    b.Property<string>("ShopperId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("shopper_id");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("CartId");

                    b.HasIndex(new[] { "ShopperId" }, "idx_orders_shopper_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasColumnType("character varying")
                        .HasColumnName("order_item_id");

                    b.Property<decimal>("PriceAtPurchaseEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_purchase_egp")
                        .HasComment("final locked-in price at checkout — independent of later product.price_egp changes");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<int>("Qty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("qty");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("size");

                    b.Property<string>("SubOrderId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("sub_order_id");

                    b.HasKey("OrderItemId")
                        .HasName("order_items_pkey");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "SubOrderId" }, "idx_order_items_sub_order_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("brand_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("category")
                        .HasComment("shirt, pants, shoes, accessory, etc.");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("character varying")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<decimal>("PriceEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_egp");

                    b.PrimitiveCollection<List<string>>("StyleTags")
                        .HasColumnType("character varying[]")
                        .HasColumnName("style_tags")
                        .HasComment("e.g. linen, casual, chino — used by Catalog-Query Tool");

                    b.HasKey("ProductId")
                        .HasName("products_pkey");

                    b.HasIndex(new[] { "BrandId" }, "idx_products_brand_id");

                    b.HasIndex(new[] { "Category" }, "idx_products_category");

                    b.HasIndex(new[] { "StyleTags" }, "idx_products_style_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "StyleTags" }, "idx_products_style_tags"), "gin");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.ProductSize", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<string>("Size")
                        .HasColumnType("character varying")
                        .HasColumnName("size")
                        .HasComment("S, M, L, XL, etc.");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer")
                        .HasColumnName("stock_qty");

                    b.HasKey("ProductId", "Size")
                        .HasName("product_sizes_pkey");

                    b.ToTable("product_sizes", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Shopper", b =>
                {
                    b.Property<string>("ShopperId")
                        .HasColumnType("character varying")
                        .HasColumnName("shopper_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("ShopperId")
                        .HasName("shoppers_pkey");

                    b.ToTable("shoppers", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.SubOrder", b =>
                {
                    b.Property<string>("SubOrderId")
                        .HasColumnType("character varying")
                        .HasColumnName("sub_order_id");

                    b.Property<string>("BrandId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("brand_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("order_id");

                    b.Property<decimal>("TotalEgp")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_egp")
                        .HasComment("FR-21 — one sub-order per brand; must equal SUM(order_items.price_at_purchase_egp * qty)");

                    b.HasKey("SubOrderId")
                        .HasName("sub_orders_pkey");

                    b.HasIndex(new[] { "BrandId" }, "idx_sub_orders_brand_id");

                    b.HasIndex(new[] { "OrderId" }, "idx_sub_orders_order_id");

                    b.ToTable("sub_orders", (string)null);
                });

            modelBuilder.Entity("OneFit.Domain.Entities.WishlistItem", b =>
                {
                    b.Property<string>("WishlistItemId")
                        .HasColumnType("text")
                        .HasColumnName("wishlist_item_id");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<decimal>("PriceAtSaveEgp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_at_save_egp");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("product_id");

                    b.Property<string>("ShopperId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("shopper_id");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("size");

                    b.HasKey("WishlistItemId");

                    b.HasIndex("ShopperId")
                        .HasDatabaseName("idx_wishlist_shopper_id");

                    b.HasIndex("ProductId", "Size");

                    b.ToTable("wishlist_items", (string)null);
                });

            modelBuilder.Entity("OneFit.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OneFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OneFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OneFit.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Alert", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Product", "Product")
                        .WithMany("Alerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_product");

                    b.HasOne("OneFit.Domain.Entities.Shopper", "Shopper")
                        .WithMany("Alerts")
                        .HasForeignKey("ShopperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_shopper");

                    b.Navigation("Product");

                    b.Navigation("Shopper");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Cart", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Shopper", "Shopper")
                        .WithMany("Carts")
                        .HasForeignKey("ShopperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carts_shopper");

                    b.Navigation("Shopper");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Brand", "Brand")
                        .WithMany("CartItems")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_brand");

                    b.HasOne("OneFit.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_cart");

                    b.HasOne("OneFit.Domain.Entities.ProductSize", "ProductSize")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId", "Size")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_items_product_size");

                    b.Navigation("Brand");

                    b.Navigation("Cart");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Order", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Cart", "Cart")
                        .WithMany("Orders")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_cart");

                    b.HasOne("OneFit.Domain.Entities.Shopper", "Shopper")
                        .WithMany("Orders")
                        .HasForeignKey("ShopperId")
                        .IsRequired()
                        .HasConstraintName("fk_orders_shopper");

                    b.Navigation("Cart");

                    b.Navigation("Shopper");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("fk_order_items_product");

                    b.HasOne("OneFit.Domain.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_sub_order");

                    b.Navigation("Product");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Product", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("fk_products_brand");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.ProductSize", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Product", "Product")
                        .WithMany("ProductSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sizes_product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.SubOrder", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Brand", "Brand")
                        .WithMany("SubOrders")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("fk_sub_orders_brand");

                    b.HasOne("OneFit.Domain.Entities.Order", "Order")
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sub_orders_order");

                    b.Navigation("Brand");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("OneFit.Domain.Entities.Shopper", "Shopper")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ShopperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneFit.Domain.Entities.ProductSize", "ProductSize")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ProductId", "Size")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSize");

                    b.Navigation("Shopper");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Brand", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Products");

                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Order", b =>
                {
                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Product", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductSizes");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.ProductSize", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.Shopper", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("OneFit.Domain.Entities.SubOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
